"""Prompt corpus.

Long, well-structured engineering prompts. Each is 250+ words with an explicit
output format so it scores near the quality ceiling. The extension's zap
formula scales linearly with tokens, so length is the dominant lever inside
the per-credit ceiling.
"""

from __future__ import annotations

LONG_PROMPT_TEMPLATES: tuple[str, ...] = (
    "You are the on-call engineer writing the post-incident review for a "
    "payments outage. Reconstruct the analysis from this timeline and system "
    "description.\n"
    "\n"
    "Timeline (all times UTC):\n"
    "- 14:02 - deploy v2.14.3 completes; the release adds a retry loop around "
    "the charge handler.\n"
    "- 14:07 - p99 latency on POST /charge climbs from 180 ms to 2.4 s.\n"
    "- 14:11 - error rate reaches 12%, almost all HTTP 504 from the upstream "
    "gateway.\n"
    "- 14:14 - on-call rolls back to v2.14.2.\n"
    "- 14:19 - latency and error rate return to baseline.\n"
    "\n"
    "The retry loop uses exponential backoff starting at 200 ms, five attempts, "
    "no jitter, and no circuit breaker. The upstream gateway enforces a 2 s "
    "request timeout and a per-merchant concurrency limit of 10 in-flight "
    "requests. The charge handler holds a database connection for the full "
    "duration of every attempt; the pool is 20 per instance across 8 "
    "instances.\n"
    "\n"
    "Produce the review with exactly these sections:\n"
    "\n"
    "1. Root cause. Explain the precise feedback loop between the retry storm "
    "and the upstream concurrency limit, step by step. Quantify the "
    "amplification.\n"
    "2. Contributing factors. Separate the conditions that made the failure "
    "possible from those that made it worse.\n"
    "3. Why staging missed it. Name the specific test that would have caught "
    "this, and explain why a plain load test would not.\n"
    "4. Remediation. Give defensible settings for jitter strategy and backoff "
    "curve, retry budget as a percentage of total requests, circuit-breaker "
    "thresholds, and a per-layer timeout budget from edge to database.\n"
    "5. Detection. The exact metric or alert that would have fired at 14:03 "
    "instead of 14:11.\n"
    "6. Prevention. One structural change that would make this class of "
    "failure impossible rather than merely less likely.\n"
    "\n"
    "Format the answer as a markdown document, one section per numbered point. "
    "End with a table comparing four retry strategies across columns: "
    "strategy, thundering-herd risk, convergence time, complexity, "
    "recommendation.",

    "I need to migrate a 400 GB PostgreSQL table from an integer primary key "
    "to a UUIDv7 primary key with zero planned downtime. The table is "
    "append-heavy at roughly 3k inserts/sec and 20k reads/sec, and it is "
    "referenced by seven foreign keys from other tables.\n"
    "\n"
    "Current state:\n"
    "- Postgres 15, single primary with two streaming replicas.\n"
    "- The table has 12 indexes, four of them partial.\n"
    "- Application code reads and writes through an ORM that assumes a serial "
    "integer id and uses it in URLs.\n"
    "- A maintenance window of at most 30 seconds is available per week.\n"
    "\n"
    "Design the migration and write it up as a numbered runbook covering:\n"
    "1. Schema strategy - added uuid column vs. full swap, effect on bloat.\n"
    "2. Backfill - batch size, sleep, replication lag monitoring, resumability.\n"
    "3. Foreign keys - keeping the seven references consistent.\n"
    "4. Cutover - the exact sequence for the 30-second window and rollback.\n"
    "5. Verification - queries that prove correctness and drop-safety metrics.\n"
    "6. Failure modes - three most likely to go wrong and their early signals.\n"
    "\n"
    "Return the runbook as markdown with one section per number, and include a "
    "table of every step with columns: step, expected duration, lock type, "
    "rollback action.",

    "Design a distributed tracing pipeline for a system of 60 microservices "
    "that currently has no tracing at all. Traffic is about 50k requests/sec "
    "at peak across three regions.\n"
    "\n"
    "Constraints:\n"
    "- Services in Go, Java, and Python, no shared framework.\n"
    "- Hard budget of 2% added p99 latency from instrumentation.\n"
    "- Trace storage budget 15 TB/month; full sampling needs ~400 TB.\n"
    "- Four on-call engineers, no prior tracing experience.\n"
    "\n"
    "Produce the design as a technical document with sections:\n"
    "1. Context propagation - format and header layout, async queue survival.\n"
    "2. Sampling - two-stage head + tail scheme fitting the 15 TB budget.\n"
    "3. Instrumentation - roll out across three languages within latency budget.\n"
    "4. Storage and query - columnar vs. search store, retention, cost model.\n"
    "5. Adoption - 90-day plan, first three dashboards, first alert.\n"
    "6. Failure modes - what breaks first at 3x traffic and graceful "
    "degradation.\n"
    "\n"
    "Format as markdown. Include a JSON example of the span envelope, and a "
    "table of sampling decisions with columns: trace class, head decision, "
    "tail decision, retention.",

    "Compare Rust and Go for a network service that terminates 200k concurrent "
    "TLS connections, parses a binary protocol, and fans out to a backend over "
    "gRPC. The service must hold connections open for hours and is memory "
    "constrained to 4 GB per instance.\n"
    "\n"
    "Give a decision-grade comparison, not a language-features list:\n"
    "1. Memory per connection - steady-state footprint per language, showing "
    "arithmetic and assumptions.\n"
    "2. Backpressure - runtime behaviour under 200k in-flight requests when "
    "the backend stalls.\n"
    "3. Tail latency - scheduler behaviour and 100 ms p99.9 risk.\n"
    "4. Binary protocol parsing - zero-copy ease and alternatives cost.\n"
    "5. Operational cost - build, binary size, cross-compilation, "
    "observability, hiring pool.\n"
    "6. Recommendation - pick one, name switch conditions, name the single "
    "measurement that would change your mind.\n"
    "\n"
    "Return the comparison as a markdown document with one section per point, "
    "and finish with a decision table with columns: criterion, Rust, Go, "
    "weight, winner.",

    "Our Kubernetes cluster runs 400 pods across 30 nodes and the autoscaler "
    "is behaving badly. Design a fix.\n"
    "\n"
    "Symptoms:\n"
    "- Scale-up takes 4-6 minutes even though pods start in 20 seconds.\n"
    "- The cluster oscillates between 22 and 30 nodes roughly every 15 "
    "minutes.\n"
    "- A batch job that runs hourly causes a spike that evicts "
    "latency-critical pods.\n"
    "- Node scale-down sometimes kills pods that are mid-request.\n"
    "\n"
    "Write the analysis and remediation in numbered sections:\n"
    "1. Scale-up latency - responsible stage and its configuration fix.\n"
    "2. Oscillation - feedback loop between HPA and cluster autoscaler and "
    "specific stabilization-window/tolerance values that stop it.\n"
    "3. Noisy neighbour - priority classes, PDBs, dedicated pools, tradeoffs.\n"
    "4. Safe scale-down - termination grace, preStop, readiness gating, and "
    "which layer owns the guarantee.\n"
    "5. Verification - metrics and load tests that prove each fix.\n"
    "\n"
    "Format as markdown. Include the HPA and cluster-autoscaler YAML and a "
    "table with columns: symptom, root stage, fix, verification metric.",

    "Design an idempotent data pipeline that ingests 5 billion events per day "
    "from a Kafka topic with at-least-once delivery, lands them in a "
    "warehouse, and must produce exactly-once aggregate tables for billing.\n"
    "\n"
    "Context:\n"
    "- Producers can and do replay partitions after a failure.\n"
    "- Events carry event_id, occurred_at, producer_id, but no global sequence.\n"
    "- Late arrivals up to 72 hours after occurred_at.\n"
    "- Billing reads aggregates daily; any double count is a financial "
    "incident.\n"
    "\n"
    "Sections:\n"
    "1. Deduplication - where and by what key, replay-with-different-timestamp "
    "behaviour.\n"
    "2. Late data - handling a 71-hour-late event without invalidating a read "
    "aggregate.\n"
    "3. Exactly-once aggregation - storage primitive and transaction boundary.\n"
    "4. Replay - safe partition reprocessing and blast-radius bounds.\n"
    "5. Reconciliation - daily source-vs-warehouse check, tolerance, on-fail.\n"
    "6. Cost - storage/compute estimate and largest lever.\n"
    "\n"
    "Format as markdown. Include the dedupe table schema and a failure-scenario "
    "table with columns: scenario, detection, recovery action, data impact.",
)


SHORT_PROMPT_TEMPLATES: tuple[str, ...] = (
    "Explain the difference between optimistic and pessimistic locking in a "
    "relational database.\n"
    "Cover: contention behaviour under load, deadlock risk, and which one "
    "suits a high-write ledger table.\n"
    "Return the answer as a markdown table with columns: Aspect, Optimistic, "
    "Pessimistic.",
    "I have a Python asyncio service that leaks file descriptors under load.\n"
    "Walk through a systematic debugging approach: what to inspect first, "
    "which metrics to graph, and how to reproduce it in a test harness.\n"
    "Format the response as a numbered checklist.",
    "Compare Rust's ownership model against C++ RAII for resource management.\n"
    "Discuss move semantics, borrow checking, destructor ordering, and the "
    "failure modes each design prevents.\n"
    "Give the output as a structured comparison with a short code example per "
    "language.",
    "Design a rate limiter for a multi-tenant HTTP API.\n"
    "Consider token bucket vs. sliding window, per-tenant fairness, Redis as "
    "shared state, and graceful degradation when the limiter is unavailable.\n"
    "Return the design as markdown with a JSON config example.",
    "My Postgres query plan switched from an index scan to a sequential scan "
    "after a data migration.\n"
    "Explain how to diagnose this with EXPLAIN ANALYZE, what statistics may be "
    "stale, and how to verify the fix.\n"
    "Provide the answer as a step-by-step procedure with example SQL.",
    "Outline a threat model for a webhook receiver endpoint.\n"
    "Cover signature verification, replay protection, SSRF from outbound "
    "callbacks, and idempotency keys.\n"
    "Return a markdown table mapping each threat to a concrete mitigation.",
)
